name: Build
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Install
        run: python3 hello.py
      - name: Install deps
        run: pip install pylint
      - name: Lint
        run: python3 -m pylint simple_code.py
