name: Check
on: push
jobs:
  start_scrits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Lint
        run: python3 -m pylint simple_code.py
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Install deps
        run: pip install -r requirements_test.txt
      - name: Test
        run: pytest